#!/bin/bash -e

export DEBIAN_FRONTEND=noninteractive

SOURCE_DIR=/var/lib/tsuru
$SOURCE_DIR/base/install

source $SOURCE_DIR/config

cp $SOURCE_DIR/glassfish41/Procfile $SOURCE_DIR/utils/Procfile
echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:webupd8team/java
apt-get update
apt-get install -y --force-yes oracle-java8-installer
apt-get install -y --force-yes maven

echo "PermitUserEnvironment yes" >> /etc/ssh/sshd_config

sed -i 's;\[ -f /home/application/apprc \] && source /home/application/apprc;#JAVA_HOME#;' /home/ubuntu/.profile
echo '[ -f /home/application/apprc ] && source /home/application/apprc' >> /home/ubuntu/.profile

### Installing GlassFish: ###

cd /tmp

wget http://download.java.net/glassfish/4.1/release/glassfish-4.1.zip

cd /usr/share

unzip /tmp/glassfish-4.1.zip

sudo chown -R ${USER}:${USER} /usr/share/glassfish4

echo "export PATH=/usr/share/glassfish4/glassfish/bin:$PATH" >> /home/ubuntu/.profile

echo "export JAVA_HOME=/usr/lib/jvm/java-8-oracle" >> /home/ubuntu/.profile

source /home/ubuntu/.profile

echo "ubuntu soft nofile 32768" >> /etc/security/limits.conf
echo "ubuntu hard nofile 65536" >> /etc/security/limits.conf

sed -i 's/\"8080\"/\"8888\"/' /usr/share/glassfish4/glassfish/domains/domain1/config/domain.xml
