#!/bin/bash -l

source /home/ubuntu/.profile

source /var/lib/tsuru/config
java_to_use="java-8-oracle"

sudo update-java-alternatives -s $java_to_use > /dev/null
sed -i "s;export JAVA_HOME.*;export JAVA_HOME=/usr/lib/jvm/$java_to_use;" /home/ubuntu/.profile
sed -i "s;#JAVA_HOME#;export JAVA_HOME=/usr/lib/jvm/$java_to_use;" /home/ubuntu/.profile

mkdir -p /home/ubuntu/.ssh
chmod 700 /home/ubuntu/.ssh
echo "JAVA_HOME=/usr/lib/jvm/$java_to_use" > /home/ubuntu/.ssh/environment

/var/lib/tsuru/base/start
